// Generated from the native app. Regenerate with scripts/sync-demo.cjs.
export const en = {
	// Splash
	"splash.tagline": "Check in with your people",
	"splash.feature1": "Share how you feel, daily",
	"splash.feature2": "See when your circle checks in",
	"splash.feature3": "Stay connected, effortlessly",
	"splash.getStarted": "Get Started",
	"splash.logIn": "Log In",
	"splash.largeTextNudge": "Hard to read? Tap for larger text",
	// Auth - Sign Up
	"signup.title": "Create account",
	"signup.subtitle": "Join your people on Inko",
	"signup.email": "Email",
	"signup.emailPlaceholder": "you@example.com",
	"signup.username": "Username",
	"signup.usernamePlaceholder": "e.g. eriksson42",
	"signup.firstName": "First name",
	"signup.firstNamePlaceholder": "Erik",
	"signup.lastName": "Last name",
	"signup.lastNamePlaceholder": "Eriksson",
	"signup.submit": "Continue",
	"signup.errorEmail": "Please enter a valid email",
	"signup.errorUsername": "Username is required",
	"signup.errorUsernameLength": "Username must be 3\u201320 characters",
	"signup.errorUsernameChars":
		"Only lowercase letters, numbers and underscores",
	"signup.errorUsernameTaken": "This username is already taken",
	"signup.errorFirstName": "First name is required",
	"signup.errorLastName": "Last name is too long",
	"signup.phone": "Phone number (optional)",
	"signup.phoneHint":
		"Add your number so friends can find you through their contacts.",
	"signup.phonePlaceholder": "+46 70 123 4567",
	"signup.errorPhone": "Please enter a valid phone number",
	"signup.errorGeneric": "Could not create account",
	// Auth - Log In
	"login.title": "Welcome back",
	"login.subtitle": "Sign in to your account",
	"login.email": "Email",
	"login.emailPlaceholder": "you@example.com",
	"login.submit": "Send Code",
	"login.otpHint": "We'll send a verification code to your email.",
	"login.errorInvalid": "Please enter a valid email",
	"login.errorGeneric": "Could not send code",
	// Auth - Verify OTP
	"verify.title": "Check your email",
	"verify.subtitle": "Enter the code sent to {{email}}",
	"verify.codeLabel": "Verification code",
	"verify.codePlaceholder": "000000",
	"verify.submit": "Verify",
	"verify.resend": "Resend code",
	"verify.errorCode": "Enter the 6-digit code",
	"verify.errorGeneric": "Could not verify code",
	// CheckInCircle
	"checkin.tapTo": "Tap to",
	"checkin.inko": "inko",
	"checkin.done": "Inkoed!",
	"checkin.tapToChange": "tap to change",
	"checkin.doneStreak": "{{count}} days in a row",
	"checkin.errorTitle": "Check-in failed",
	"checkin.errorGeneric": "Could not save your check-in. Please try again.",
	"checkin.errorSession": "You need to sign in again.",
	// EmojiPicker
	"emoji.title": "How are you today?",
	"emoji.subtitle": "Pick up to 3",
	"emoji.subtitleFree": "Pick one",
	"emoji.done": "Done",
	// ConnectionCard
	"connection.notOnInko": "Not on Inko yet",
	"connection.onVacation": "On vacation",
	"connection.removeTitle": "Remove {{name}}?",
	"connection.removeMessage": "They won't be notified.",
	"connection.remove": "Remove",
	"connection.block": "Block",
	"connection.blockTitle": "Block {{name}}?",
	"connection.blockMessage": "They won't be able to add you to their circle.",
	"connection.addNickname": "Add nickname",
	"connection.editNickname": "Edit nickname",
	"connection.nicknamePlaceholder": "Enter a nickname",
	"connection.nicknameSave": "Save",
	"connection.nicknameTitle": "Nickname for {{name}}",
	"connection.missedDeadline": "Missed deadline",
	"connection.days": "{{count}} days",
	// ConnectionsList
	"circle.title": "Your Circle",
	"circle.empty": "Your circle is empty",
	"circle.emptyHint": "Tap the people icon to add someone",
	"circle.emptyAction": "Add people",
	"circle.errorTitle": "Could not load your circle",
	"circle.errorRetry": "Try again",
	"circle.complete": "Circle complete!",
	// Settings
	"settings.title": "Settings",
	"settings.account": "Account",
	"settings.username": "Username",
	"settings.emailAddress": "Email",
	"settings.name": "Name",
	"settings.timezone": "Timezone",
	"settings.selectTimezone": "Select Timezone",
	"settings.searchTimezone": "Search timezones...",
	"settings.errorTimezone": "Could not update timezone",
	"settings.dailyDeadline": "Daily Deadline",
	"settings.change": "change",
	"settings.reminderHint": "Reminders at 5h, 1h and 15 min before.",
	"settings.vacationMode": "Vacation Mode",
	"settings.vacationHint":
		"On for 1 week. Pauses reminders & preserves streaks.",
	"settings.vacationStart": "Start 7-day vacation?",
	"settings.vacationStartConfirm": "Streaks will be preserved.",
	"settings.vacationEndEarly": "End vacation early?",
	"settings.vacationDaysLeft": "{{count}} days remaining",
	"settings.selectLanguage": "Select Language",
	"settings.language": "Language",
	"settings.signOut": "Sign Out",
	"settings.deleteAccount": "Delete Account",
	"settings.version": "inko v{{version}}",
	"settings.signOutTitle": "Sign out",
	"settings.signOutConfirm": "Are you sure?",
	"settings.deleteTitle": "Delete account",
	"settings.deleteMessage":
		"This will permanently delete your account and all data. This cannot be undone.",
	"settings.delete": "Delete",
	"settings.updateFailed": "Update failed",
	"settings.errorVacation": "Could not update vacation mode",
	"settings.errorDeadline": "Could not update deadline time",
	"settings.errorLanguage": "Could not update language",
	"settings.circleComplete": "Circle Complete Notification",
	"settings.circleCompleteHint":
		"Get notified when everyone in your circle has checked in.",
	"settings.largeText": "Large Text",
	"settings.largeTextHint": "Increases text size for easier reading.",
	"settings.privacyPolicy": "Privacy Policy",
	"settings.plan": "Plan",
	"settings.premiumActive": "Premium",
	"settings.upgradeToPremium": "Upgrade to Premium",
	// TimePickerModal
	"timePicker.title": "Set Daily Deadline",
	// Add Person
	"addPerson.title": "Add Person",
	"addPerson.fromContacts": "From Contacts",
	"addPerson.usernameLabel": "Username",
	"addPerson.usernamePlaceholder": "e.g. eriksson42",
	"addPerson.add": "Add",
	"addPerson.errorUsername": "Enter a username",
	"addPerson.errorNotFound": "No user found with that username",
	"addPerson.errorAdd": "Could not add person",
	"addPerson.errorGeneric": "Something went wrong",
	// Contacts
	"contacts.title": "Add People",
	"contacts.search": "Search contacts...",
	"contacts.onInko": "ON INKO ({{count}})",
	"contacts.invite": "INVITE ({{count}})",
	"contacts.onInkoBadge": "on inko",
	"contacts.addToCircle": "Add {{count}} to circle",
	"contacts.inviteFriends": "Invite friends",
	"contacts.inviteButton": "Invite",
	"contacts.permissionTitle": "Contacts access needed",
	"contacts.permissionMessage":
		"Allow Inko to access your contacts to find people you know.",
	"contacts.openSettings": "Open Settings",
	"contacts.noContacts": "No contacts found",
	"contacts.manualEntry": "Add by username",
	"contacts.noContactsMessage":
		"No contacts with valid phone numbers were found on your device.",
	// Date/time
	"time.justNow": "just now",
	"time.minutesAgo": "{{count}}m ago",
	"time.hoursAgo": "{{count}}h ago",
	// Share invite
	"invite.message":
		"Hey! I'm using Inko to check in with my circle every day. Join me!\n\nMy username: {{username}}\n\nAndroid: https://play.google.com/store/apps/details?id=com.inko.app\niOS: https://apps.apple.com/app/id6759858427",
	// Notification action buttons
	"notification.action.inkoNow": "Inko now",
	"notification.action.reachOut": "Reach out",
	// Notifications
	"notifications.requiredTitle": "Notifications required",
	"notifications.requiredMessage":
		"Inko needs notifications to remind you to check in and let you know when your circle is complete.",
	"notifications.openSettings": "Open Settings",
	"notifications.statusEnabled": "Enabled",
	"notifications.statusDisabled": "Disabled — tap to fix",
	"notifications.pushNotifications": "Push notifications",
	// Spotlight
	"spotlight.step1Title": "Welcome to Inko",
	"spotlight.step1Subtitle":
		"A daily check-in with your people.\nOne emoji per day. That's it.",
	"spotlight.step2Title": "Tap. Feel. Share.",
	"spotlight.step2Subtitle":
		"Tap the heart and pick up to 3 emojis\nthat capture your day.",
	"spotlight.step3Title": "Your Circle",
	"spotlight.step3Subtitle":
		"Add the people who matter.\nSee when they check in.",
	"spotlight.step4Title": "Stay on Track",
	"spotlight.step4Subtitle":
		"Get gentle reminders before your deadline.\nAt midnight, it resets. Need a break?\nTurn on Vacation Mode in settings.",
	"spotlight.next": "Next",
	"spotlight.letsGo": "Let's go",
	// Streak
	"streak.own": "{{count}}-day streak",
	// Premium
	"premium.title": "Unlock Premium",
	"premium.subtitle": "Get the full Inko experience.",
	"premium.featureEmojis": "50 emojis to choose from",
	"premium.featureMultiEmoji": "Pick up to 3 emojis per check-in",
	"premium.unlock": "Unlock for {{price}}",
	"premium.unlockWeb": "Unlock Premium",
	"premium.restore": "Restore purchase",
	"premium.restoring": "Restoring...",
	// Common
	"common.cancel": "Cancel",
	"common.close": "Close",
	// Language names
	"language.en": "English",
	"language.sv": "Svenska",
	"language.es": "Espa\u00f1ol",
	"language.pt": "Portugu\u00eas",
};
export const sv = {
	// Splash
	"splash.tagline": "Kolla in med dina n\u00e4ra",
	"splash.feature1": "Dela hur du m\u00e5r, varje dag",
	"splash.feature2": "Se n\u00e4r din cirkel inkar",
	"splash.feature3": "H\u00e5ll kontakten, utan anstr\u00e4ngning",
	"splash.getStarted": "Kom ig\u00e5ng",
	"splash.logIn": "Logga in",
	"splash.largeTextNudge":
		"Sv\u00e5rt att l\u00e4sa? Tryck f\u00f6r st\u00f6rre text",
	// Auth - Sign Up
	"signup.title": "Skapa konto",
	"signup.subtitle": "G\u00e5 med p\u00e5 Inko",
	"signup.email": "E-post",
	"signup.emailPlaceholder": "du@exempel.se",
	"signup.username": "Anv\u00e4ndarnamn",
	"signup.usernamePlaceholder": "t.ex. eriksson42",
	"signup.firstName": "F\u00f6rnamn",
	"signup.firstNamePlaceholder": "Erik",
	"signup.lastName": "Efternamn",
	"signup.lastNamePlaceholder": "Eriksson",
	"signup.submit": "Forts\u00e4tt",
	"signup.errorEmail": "Ange en giltig e-postadress",
	"signup.errorUsername": "Anv\u00e4ndarnamn kr\u00e4vs",
	"signup.errorUsernameLength":
		"Anv\u00e4ndarnamn m\u00e5ste vara 3\u201320 tecken",
	"signup.errorUsernameChars":
		"Bara sm\u00e5 bokst\u00e4ver, siffror och understreck",
	"signup.errorUsernameTaken":
		"Det h\u00e4r anv\u00e4ndarnamnet \u00e4r redan taget",
	"signup.errorFirstName": "F\u00f6rnamn kr\u00e4vs",
	"signup.errorLastName": "Efternamnet \u00e4r f\u00f6r l\u00e5ngt",
	"signup.phone": "Telefonnummer (valfritt)",
	"signup.phoneHint":
		"Lägg till ditt nummer så att vänner kan hitta dig via sina kontakter.",
	"signup.phonePlaceholder": "+46 70 123 4567",
	"signup.errorPhone": "Ange ett giltigt telefonnummer",
	"signup.errorGeneric": "Kunde inte skapa konto",
	// Auth - Log In
	"login.title": "V\u00e4lkommen tillbaka",
	"login.subtitle": "Logga in p\u00e5 ditt konto",
	"login.email": "E-post",
	"login.emailPlaceholder": "du@exempel.se",
	"login.submit": "Skicka kod",
	"login.otpHint": "Vi skickar en verifieringskod till din e-post.",
	"login.errorInvalid": "Ange en giltig e-postadress",
	"login.errorGeneric": "Kunde inte skicka kod",
	// Auth - Verify OTP
	"verify.title": "Kolla din e-post",
	"verify.subtitle": "Ange koden som skickades till {{email}}",
	"verify.codeLabel": "Verifieringskod",
	"verify.codePlaceholder": "000000",
	"verify.submit": "Verifiera",
	"verify.resend": "Skicka igen",
	"verify.errorCode": "Ange den 6-siffriga koden",
	"verify.errorGeneric": "Kunde inte verifiera koden",
	// CheckInCircle
	"checkin.tapTo": "Tryck f\u00f6r att",
	"checkin.inko": "inka",
	"checkin.done": "Inkat!",
	"checkin.tapToChange": "tryck för att ändra",
	"checkin.doneStreak": "{{count}} dagar i rad",
	"checkin.errorTitle": "Incheckningen misslyckades",
	"checkin.errorGeneric":
		"Kunde inte spara din incheckning. F\u00f6rs\u00f6k igen.",
	"checkin.errorSession": "Du beh\u00f6ver logga in igen.",
	// EmojiPicker
	"emoji.title": "Hur m\u00e5r du idag?",
	"emoji.subtitle": "V\u00e4lj upp till 3",
	"emoji.subtitleFree": "V\u00e4lj en",
	"emoji.done": "Klar",
	// ConnectionCard
	"connection.notOnInko": "Inte p\u00e5 Inko \u00e4n",
	"connection.onVacation": "P\u00e5 semester",
	"connection.removeTitle": "Ta bort {{name}}?",
	"connection.removeMessage": "De kommer inte meddelas.",
	"connection.remove": "Ta bort",
	"connection.block": "Blockera",
	"connection.blockTitle": "Blockera {{name}}?",
	"connection.blockMessage":
		"De kommer inte kunna l\u00e4gga till dig i sin cirkel.",
	"connection.addNickname": "L\u00e4gg till smeknamn",
	"connection.editNickname": "\u00c4ndra smeknamn",
	"connection.nicknamePlaceholder": "Ange ett smeknamn",
	"connection.nicknameSave": "Spara",
	"connection.nicknameTitle": "Smeknamn f\u00f6r {{name}}",
	"connection.missedDeadline": "Missade deadline",
	"connection.days": "{{count}} dagar",
	// ConnectionsList
	"circle.title": "Din cirkel",
	"circle.empty": "Din cirkel \u00e4r tom",
	"circle.emptyHint":
		"Tryck p\u00e5 personikonen f\u00f6r att l\u00e4gga till n\u00e5gon",
	"circle.emptyAction": "L\u00e4gg till personer",
	"circle.errorTitle": "Kunde inte ladda din cirkel",
	"circle.errorRetry": "F\u00f6rs\u00f6k igen",
	"circle.complete": "Cirkeln \u00e4r komplett!",
	// Settings
	"settings.title": "Inst\u00e4llningar",
	"settings.account": "Konto",
	"settings.username": "Anv\u00e4ndarnamn",
	"settings.emailAddress": "E-post",
	"settings.name": "Namn",
	"settings.timezone": "Tidszon",
	"settings.selectTimezone": "Välj tidszon",
	"settings.searchTimezone": "Sök tidszoner...",
	"settings.errorTimezone": "Kunde inte uppdatera tidszon",
	"settings.dailyDeadline": "Daglig deadline",
	"settings.change": "\u00e4ndra",
	"settings.reminderHint": "P\u00e5minnelser 5h, 1h och 15 min innan.",
	"settings.vacationMode": "Semesterl\u00e4ge",
	"settings.vacationHint":
		"P\u00e5 i 1 vecka. Pausar p\u00e5minnelser & bevarar streaks.",
	"settings.vacationStart": "Starta 7 dagars semester?",
	"settings.vacationStartConfirm": "Streaks bevaras.",
	"settings.vacationEndEarly": "Avsluta semestern i f\u00f6rtid?",
	"settings.vacationDaysLeft": "{{count}} dagar kvar",
	"settings.selectLanguage": "V\u00e4lj spr\u00e5k",
	"settings.language": "Spr\u00e5k",
	"settings.signOut": "Logga ut",
	"settings.deleteAccount": "Radera konto",
	"settings.version": "inko v{{version}}",
	"settings.signOutTitle": "Logga ut",
	"settings.signOutConfirm": "\u00c4r du s\u00e4ker?",
	"settings.deleteTitle": "Radera konto",
	"settings.deleteMessage":
		"Detta raderar permanent ditt konto och all data. Det g\u00e5r inte att \u00e5ngra.",
	"settings.delete": "Radera",
	"settings.updateFailed": "Uppdatering misslyckades",
	"settings.errorVacation": "Kunde inte uppdatera semesterl\u00e4ge",
	"settings.errorDeadline": "Kunde inte uppdatera deadline",
	"settings.errorLanguage": "Kunde inte uppdatera spr\u00e5k",
	"settings.circleComplete": "Cirkel komplett-notis",
	"settings.circleCompleteHint":
		"Bli notifierad n\u00e4r alla i din cirkel har checkat in.",
	"settings.largeText": "Stor text",
	"settings.largeTextHint":
		"F\u00f6rstorar texten f\u00f6r enklare l\u00e4sning.",
	"settings.privacyPolicy": "Integritetspolicy",
	"settings.plan": "Plan",
	"settings.premiumActive": "Premium",
	"settings.upgradeToPremium": "Uppgradera till Premium",
	// TimePickerModal
	"timePicker.title": "St\u00e4ll in daglig deadline",
	// Add Person
	"addPerson.title": "L\u00e4gg till person",
	"addPerson.fromContacts": "Fr\u00e5n kontakter",
	"addPerson.usernameLabel": "Anv\u00e4ndarnamn",
	"addPerson.usernamePlaceholder": "t.ex. eriksson42",
	"addPerson.add": "L\u00e4gg till",
	"addPerson.errorUsername": "Ange ett anv\u00e4ndarnamn",
	"addPerson.errorNotFound":
		"Ingen anv\u00e4ndare hittades med det anv\u00e4ndarnamnet",
	"addPerson.errorAdd": "Kunde inte l\u00e4gga till person",
	"addPerson.errorGeneric": "N\u00e5got gick fel",
	// Contacts
	"contacts.title": "L\u00e4gg till personer",
	"contacts.search": "S\u00f6k kontakter...",
	"contacts.onInko": "P\u00c5 INKO ({{count}})",
	"contacts.invite": "BJUD IN ({{count}})",
	"contacts.onInkoBadge": "p\u00e5 inko",
	"contacts.addToCircle": "L\u00e4gg till {{count}} i cirkeln",
	"contacts.inviteFriends": "Bjud in v\u00e4nner",
	"contacts.inviteButton": "Bjud in",
	"contacts.permissionTitle": "Kontakt\u00e5tkomst beh\u00f6vs",
	"contacts.permissionMessage":
		"Till\u00e5t Inko att komma \u00e5t dina kontakter f\u00f6r att hitta personer du k\u00e4nner.",
	"contacts.openSettings": "\u00d6ppna inst\u00e4llningar",
	"contacts.noContacts": "Inga kontakter hittades",
	"contacts.manualEntry": "L\u00e4gg till med anv\u00e4ndarnamn",
	"contacts.noContactsMessage":
		"Inga kontakter med giltiga telefonnummer hittades p\u00e5 din enhet.",
	// Date/time
	"time.justNow": "just nu",
	"time.minutesAgo": "{{count}}m sedan",
	"time.hoursAgo": "{{count}}h sedan",
	// Share invite
	"invite.message":
		"Hej! Jag anv\u00e4nder Inko f\u00f6r att checka in med min cirkel varje dag. H\u00e4ng med!\n\nMitt anv\u00e4ndarnamn: {{username}}\n\nAndroid: https://play.google.com/store/apps/details?id=com.inko.app\niOS: https://apps.apple.com/app/id6759858427",
	// Notification action buttons
	"notification.action.inkoNow": "Inka nu",
	"notification.action.reachOut": "N\u00e5 ut",
	// Notifications
	"notifications.requiredTitle": "Aviseringar kr\u00e4vs",
	"notifications.requiredMessage":
		"Inko beh\u00f6ver aviseringar f\u00f6r att p\u00e5minna dig att inka och meddela dig n\u00e4r din cirkel \u00e4r komplett.",
	"notifications.openSettings": "Öppna inställningar",
	"notifications.statusEnabled": "Aktiverade",
	"notifications.statusDisabled": "Inaktiverade — tryck för att fixa",
	"notifications.pushNotifications": "Push-aviseringar",
	// Spotlight
	"spotlight.step1Title": "V\u00e4lkommen till Inko",
	"spotlight.step1Subtitle":
		"En daglig incheckning med dina n\u00e4ra.\nEn emoji per dag. Det \u00e4r allt.",
	"spotlight.step2Title": "Tryck. K\u00e4nn. Dela.",
	"spotlight.step2Subtitle":
		"Tryck p\u00e5 hj\u00e4rtat och v\u00e4lj upp till 3 emojis\nsom f\u00e5ngar din dag.",
	"spotlight.step3Title": "Din cirkel",
	"spotlight.step3Subtitle":
		"L\u00e4gg till de som betyder n\u00e5got.\nSe n\u00e4r de inkar.",
	"spotlight.step4Title": "H\u00e5ll koll",
	"spotlight.step4Subtitle":
		"F\u00e5 p\u00e5minnelser innan din deadline.\nVid midnatt nollst\u00e4lls allt. Beh\u00f6ver du en paus?\nSl\u00e5 p\u00e5 Semesterl\u00e4ge i inst\u00e4llningar.",
	"spotlight.next": "N\u00e4sta",
	"spotlight.letsGo": "K\u00f6r ig\u00e5ng",
	// Streak
	"streak.own": "{{count}} dagars streak",
	// Premium
	"premium.title": "L\u00e5s upp Premium",
	"premium.subtitle": "F\u00e5 hela Inko-upplevelsen.",
	"premium.featureEmojis": "50 emojis att v\u00e4lja mellan",
	"premium.featureMultiEmoji": "V\u00e4lj upp till 3 emojis per incheckning",
	"premium.unlock": "L\u00e5s upp f\u00f6r {{price}}",
	"premium.unlockWeb": "L\u00e5s upp Premium",
	"premium.restore": "\u00c5terst\u00e4ll k\u00f6p",
	"premium.restoring": "\u00c5terst\u00e4ller...",
	// Common
	"common.cancel": "Avbryt",
	"common.close": "Stäng",
	// Language names
	"language.en": "English",
	"language.sv": "Svenska",
	"language.es": "Espa\u00f1ol",
	"language.pt": "Portugu\u00eas",
};
export const es = {
	// Splash
	"splash.tagline": "Haz check-in con tu gente",
	"splash.feature1": "Comparte c\u00f3mo te sientes, cada d\u00eda",
	"splash.feature2": "Mira cuando tu c\u00edrculo hace check-in",
	"splash.feature3": "Mant\u00e9n el contacto, sin esfuerzo",
	"splash.getStarted": "Comenzar",
	"splash.logIn": "Iniciar sesi\u00f3n",
	"splash.largeTextNudge":
		"\u00bfDif\u00edcil de leer? Toca para texto m\u00e1s grande",
	// Auth - Sign Up
	"signup.title": "Crear cuenta",
	"signup.subtitle": "\u00danete a tu gente en Inko",
	"signup.email": "Correo electr\u00f3nico",
	"signup.emailPlaceholder": "tu@ejemplo.com",
	"signup.username": "Nombre de usuario",
	"signup.usernamePlaceholder": "ej. eriksson42",
	"signup.firstName": "Nombre",
	"signup.firstNamePlaceholder": "Erik",
	"signup.lastName": "Apellido",
	"signup.lastNamePlaceholder": "Eriksson",
	"signup.submit": "Continuar",
	"signup.errorEmail": "Ingresa un correo electr\u00f3nico v\u00e1lido",
	"signup.errorUsername": "Se requiere nombre de usuario",
	"signup.errorUsernameLength":
		"El nombre de usuario debe tener entre 3 y 20 caracteres",
	"signup.errorUsernameChars":
		"Solo letras min\u00fasculas, n\u00fameros y guiones bajos",
	"signup.errorUsernameTaken": "Este nombre de usuario ya est\u00e1 en uso",
	"signup.errorFirstName": "Se requiere nombre",
	"signup.errorLastName": "El apellido es demasiado largo",
	"signup.phone": "N\u00famero de tel\u00e9fono (opcional)",
	"signup.phoneHint":
		"Agrega tu n\u00famero para que tus amigos te encuentren a trav\u00e9s de sus contactos.",
	"signup.phonePlaceholder": "+34 612 345 678",
	"signup.errorPhone": "Ingresa un n\u00famero de tel\u00e9fono v\u00e1lido",
	"signup.errorGeneric": "No se pudo crear la cuenta",
	// Auth - Log In
	"login.title": "Bienvenido de vuelta",
	"login.subtitle": "Inicia sesi\u00f3n en tu cuenta",
	"login.email": "Correo electr\u00f3nico",
	"login.emailPlaceholder": "tu@ejemplo.com",
	"login.submit": "Enviar c\u00f3digo",
	"login.otpHint":
		"Te enviaremos un c\u00f3digo de verificaci\u00f3n a tu correo.",
	"login.errorInvalid": "Ingresa un correo electr\u00f3nico v\u00e1lido",
	"login.errorGeneric": "No se pudo enviar el c\u00f3digo",
	// Auth - Verify OTP
	"verify.title": "Revisa tu correo",
	"verify.subtitle": "Ingresa el c\u00f3digo enviado a {{email}}",
	"verify.codeLabel": "C\u00f3digo de verificaci\u00f3n",
	"verify.codePlaceholder": "000000",
	"verify.submit": "Verificar",
	"verify.resend": "Reenviar c\u00f3digo",
	"verify.errorCode": "Ingresa el c\u00f3digo de 6 d\u00edgitos",
	"verify.errorGeneric": "No se pudo verificar el c\u00f3digo",
	// CheckInCircle
	"checkin.tapTo": "Toca para",
	"checkin.inko": "inkear",
	"checkin.done": "\u00a1Inkeaste!",
	"checkin.tapToChange": "toca para cambiar",
	"checkin.doneStreak": "{{count}} d\u00edas seguidos",
	"checkin.errorTitle": "Error al hacer check-in",
	"checkin.errorGeneric": "No se pudo guardar tu check-in. Intenta de nuevo.",
	"checkin.errorSession": "Necesitas iniciar sesi\u00f3n de nuevo.",
	// EmojiPicker
	"emoji.title": "\u00bfC\u00f3mo est\u00e1s hoy?",
	"emoji.subtitle": "Elige hasta 3",
	"emoji.subtitleFree": "Elige uno",
	"emoji.done": "Listo",
	// ConnectionCard
	"connection.notOnInko": "No est\u00e1 en Inko a\u00fan",
	"connection.onVacation": "De vacaciones",
	"connection.removeTitle": "\u00bfEliminar a {{name}}?",
	"connection.removeMessage": "No ser\u00e1n notificados.",
	"connection.remove": "Eliminar",
	"connection.block": "Bloquear",
	"connection.blockTitle": "\u00bfBloquear a {{name}}?",
	"connection.blockMessage": "No podr\u00e1n agregarte a su c\u00edrculo.",
	"connection.addNickname": "A\u00f1adir apodo",
	"connection.editNickname": "Cambiar apodo",
	"connection.nicknamePlaceholder": "Escribe un apodo",
	"connection.nicknameSave": "Guardar",
	"connection.nicknameTitle": "Apodo para {{name}}",
	"connection.missedDeadline": "Hora l\u00edmite pasada",
	"connection.days": "{{count}} d\u00edas",
	// ConnectionsList
	"circle.title": "Tu C\u00edrculo",
	"circle.empty": "Tu c\u00edrculo est\u00e1 vac\u00edo",
	"circle.emptyHint": "Toca el \u00edcono de personas para agregar a alguien",
	"circle.emptyAction": "Agregar personas",
	"circle.errorTitle": "No se pudo cargar tu c\u00edrculo",
	"circle.errorRetry": "Intentar de nuevo",
	"circle.complete": "\u00a1C\u00edrculo completo!",
	// Settings
	"settings.title": "Ajustes",
	"settings.account": "Cuenta",
	"settings.username": "Nombre de usuario",
	"settings.emailAddress": "Correo electr\u00f3nico",
	"settings.name": "Nombre",
	"settings.timezone": "Zona horaria",
	"settings.selectTimezone": "Seleccionar zona horaria",
	"settings.searchTimezone": "Buscar zonas horarias...",
	"settings.errorTimezone": "No se pudo actualizar la zona horaria",
	"settings.dailyDeadline": "Hora l\u00edmite diaria",
	"settings.change": "cambiar",
	"settings.reminderHint": "Recordatorios a 5h, 1h y 15 min antes.",
	"settings.vacationMode": "Modo vacaciones",
	"settings.vacationHint":
		"Activo por 1 semana. Pausa recordatorios y conserva rachas.",
	"settings.vacationStart": "\u00bfIniciar vacaciones de 7 d\u00edas?",
	"settings.vacationStartConfirm": "Las rachas se conservar\u00e1n.",
	"settings.vacationEndEarly": "\u00bfTerminar vacaciones antes?",
	"settings.vacationDaysLeft": "{{count}} d\u00edas restantes",
	"settings.selectLanguage": "Seleccionar idioma",
	"settings.language": "Idioma",
	"settings.signOut": "Cerrar sesi\u00f3n",
	"settings.deleteAccount": "Eliminar cuenta",
	"settings.version": "inko v{{version}}",
	"settings.signOutTitle": "Cerrar sesi\u00f3n",
	"settings.signOutConfirm": "\u00bfEst\u00e1s seguro?",
	"settings.deleteTitle": "Eliminar cuenta",
	"settings.deleteMessage":
		"Esto eliminar\u00e1 permanentemente tu cuenta y todos tus datos. No se puede deshacer.",
	"settings.delete": "Eliminar",
	"settings.updateFailed": "Error al actualizar",
	"settings.errorVacation": "No se pudo actualizar el modo vacaciones",
	"settings.errorDeadline": "No se pudo actualizar la hora l\u00edmite",
	"settings.errorLanguage": "No se pudo actualizar el idioma",
	"settings.circleComplete": "Notificaci\u00f3n de c\u00edrculo completo",
	"settings.circleCompleteHint":
		"Recibe una notificaci\u00f3n cuando todos en tu c\u00edrculo hayan hecho check-in.",
	"settings.largeText": "Texto grande",
	"settings.largeTextHint":
		"Aumenta el tama\u00f1o del texto para facilitar la lectura.",
	"settings.privacyPolicy": "Pol\u00edtica de privacidad",
	"settings.plan": "Plan",
	"settings.premiumActive": "Premium",
	"settings.upgradeToPremium": "Mejorar a Premium",
	// TimePickerModal
	"timePicker.title": "Establecer hora l\u00edmite diaria",
	// Add Person
	"addPerson.title": "Agregar persona",
	"addPerson.fromContacts": "De contactos",
	"addPerson.usernameLabel": "Nombre de usuario",
	"addPerson.usernamePlaceholder": "ej. eriksson42",
	"addPerson.add": "Agregar",
	"addPerson.errorUsername": "Ingresa un nombre de usuario",
	"addPerson.errorNotFound": "No se encontr\u00f3 un usuario con ese nombre",
	"addPerson.errorAdd": "No se pudo agregar a la persona",
	"addPerson.errorGeneric": "Algo sali\u00f3 mal",
	// Contacts
	"contacts.title": "Agregar personas",
	"contacts.search": "Buscar contactos...",
	"contacts.onInko": "EN INKO ({{count}})",
	"contacts.invite": "INVITAR ({{count}})",
	"contacts.onInkoBadge": "en inko",
	"contacts.addToCircle": "Agregar {{count}} al c\u00edrculo",
	"contacts.inviteFriends": "Invitar amigos",
	"contacts.inviteButton": "Invitar",
	"contacts.permissionTitle": "Se necesita acceso a contactos",
	"contacts.permissionMessage":
		"Permite a Inko acceder a tus contactos para encontrar personas que conoces.",
	"contacts.openSettings": "Abrir Ajustes",
	"contacts.noContacts": "No se encontraron contactos",
	"contacts.manualEntry": "Agregar por nombre de usuario",
	"contacts.noContactsMessage":
		"No se encontraron contactos con n\u00fameros de tel\u00e9fono v\u00e1lidos en tu dispositivo.",
	// Date/time
	"time.justNow": "justo ahora",
	"time.minutesAgo": "hace {{count}}m",
	"time.hoursAgo": "hace {{count}}h",
	// Share invite
	"invite.message":
		"\u00a1Hola! Uso Inko para hacer check-in con mi c\u00edrculo todos los d\u00edas. \u00a1\u00danete!\n\nMi usuario: {{username}}\n\nAndroid: https://play.google.com/store/apps/details?id=com.inko.app\niOS: https://apps.apple.com/app/id6759858427",
	// Notification action buttons
	"notification.action.inkoNow": "Inkea ahora",
	"notification.action.reachOut": "Contactar",
	// Notifications
	"notifications.requiredTitle": "Se requieren notificaciones",
	"notifications.requiredMessage":
		"Inko necesita notificaciones para recordarte inkear y avisarte cuando tu c\u00edrculo est\u00e9 completo.",
	"notifications.openSettings": "Abrir Ajustes",
	"notifications.statusEnabled": "Activadas",
	"notifications.statusDisabled": "Desactivadas — toca para arreglar",
	"notifications.pushNotifications": "Notificaciones push",
	// Spotlight
	"spotlight.step1Title": "Bienvenido a Inko",
	"spotlight.step1Subtitle":
		"Un check-in diario con tu gente.\nUn emoji por d\u00eda. Eso es todo.",
	"spotlight.step2Title": "Toca. Siente. Comparte.",
	"spotlight.step2Subtitle":
		"Toca el coraz\u00f3n y elige hasta 3 emojis\nque capturen tu d\u00eda.",
	"spotlight.step3Title": "Tu C\u00edrculo",
	"spotlight.step3Subtitle":
		"Agrega a las personas que importan.\nMira cuando hacen check-in.",
	"spotlight.step4Title": "Mant\u00e9nte al d\u00eda",
	"spotlight.step4Subtitle":
		"Recibe recordatorios antes de tu hora l\u00edmite.\nA medianoche, se reinicia. \u00bfNecesitas un descanso?\nActiva Modo Vacaciones en ajustes.",
	"spotlight.next": "Siguiente",
	"spotlight.letsGo": "Vamos",
	// Streak
	"streak.own": "Racha de {{count}} d\u00edas",
	// Premium
	"premium.title": "Desbloquear Premium",
	"premium.subtitle": "Obt\u00e9n la experiencia completa de Inko.",
	"premium.featureEmojis": "50 emojis para elegir",
	"premium.featureMultiEmoji": "Elige hasta 3 emojis por check-in",
	"premium.unlock": "Desbloquear por {{price}}",
	"premium.unlockWeb": "Desbloquear Premium",
	"premium.restore": "Restaurar compra",
	"premium.restoring": "Restaurando...",
	// Common
	"common.cancel": "Cancelar",
	"common.close": "Cerrar",
	// Language names
	"language.en": "English",
	"language.sv": "Svenska",
	"language.es": "Espa\u00f1ol",
	"language.pt": "Portugu\u00eas",
};
export const pt = {
	// Splash
	"splash.tagline": "Fa\u00e7a check-in com sua galera",
	"splash.feature1": "Compartilhe como voc\u00ea est\u00e1, todo dia",
	"splash.feature2": "Veja quando seu c\u00edrculo faz check-in",
	"splash.feature3": "Fique conectado, sem esfor\u00e7o",
	"splash.getStarted": "Come\u00e7ar",
	"splash.logIn": "Entrar",
	"splash.largeTextNudge": "Dif\u00edcil de ler? Toque para texto maior",
	// Auth - Sign Up
	"signup.title": "Criar conta",
	"signup.subtitle": "Junte-se ao seu pessoal no Inko",
	"signup.email": "E-mail",
	"signup.emailPlaceholder": "voce@exemplo.com",
	"signup.username": "Nome de usu\u00e1rio",
	"signup.usernamePlaceholder": "ex. eriksson42",
	"signup.firstName": "Nome",
	"signup.firstNamePlaceholder": "Erik",
	"signup.lastName": "Sobrenome",
	"signup.lastNamePlaceholder": "Eriksson",
	"signup.submit": "Continuar",
	"signup.errorEmail": "Digite um e-mail v\u00e1lido",
	"signup.errorUsername": "Nome de usu\u00e1rio \u00e9 obrigat\u00f3rio",
	"signup.errorUsernameLength":
		"Nome de usu\u00e1rio deve ter entre 3 e 20 caracteres",
	"signup.errorUsernameChars":
		"Apenas letras min\u00fasculas, n\u00fameros e sublinhados",
	"signup.errorUsernameTaken":
		"Este nome de usu\u00e1rio j\u00e1 est\u00e1 em uso",
	"signup.errorFirstName": "Nome \u00e9 obrigat\u00f3rio",
	"signup.errorLastName": "Sobrenome \u00e9 longo demais",
	"signup.phone": "Telefone (opcional)",
	"signup.phoneHint":
		"Adicione seu número para que amigos te encontrem pelos contatos.",
	"signup.phonePlaceholder": "+55 11 91234 5678",
	"signup.errorPhone": "Digite um n\u00famero de telefone v\u00e1lido",
	"signup.errorGeneric": "N\u00e3o foi poss\u00edvel criar a conta",
	// Auth - Log In
	"login.title": "Bem-vindo de volta",
	"login.subtitle": "Entre na sua conta",
	"login.email": "E-mail",
	"login.emailPlaceholder": "voce@exemplo.com",
	"login.submit": "Enviar c\u00f3digo",
	"login.otpHint":
		"Enviaremos um c\u00f3digo de verifica\u00e7\u00e3o para seu e-mail.",
	"login.errorInvalid": "Digite um e-mail v\u00e1lido",
	"login.errorGeneric": "N\u00e3o foi poss\u00edvel enviar o c\u00f3digo",
	// Auth - Verify OTP
	"verify.title": "Verifique seu e-mail",
	"verify.subtitle": "Digite o c\u00f3digo enviado para {{email}}",
	"verify.codeLabel": "C\u00f3digo de verifica\u00e7\u00e3o",
	"verify.codePlaceholder": "000000",
	"verify.submit": "Verificar",
	"verify.resend": "Reenviar c\u00f3digo",
	"verify.errorCode": "Digite o c\u00f3digo de 6 d\u00edgitos",
	"verify.errorGeneric": "N\u00e3o foi poss\u00edvel verificar o c\u00f3digo",
	// CheckInCircle
	"checkin.tapTo": "Toque para",
	"checkin.inko": "inkar",
	"checkin.done": "Inkou!",
	"checkin.tapToChange": "toque para mudar",
	"checkin.doneStreak": "{{count}} dias seguidos",
	"checkin.errorTitle": "Falha no check-in",
	"checkin.errorGeneric":
		"N\u00e3o foi poss\u00edvel salvar seu check-in. Tente novamente.",
	"checkin.errorSession": "Voc\u00ea precisa entrar novamente.",
	// EmojiPicker
	"emoji.title": "Como voc\u00ea est\u00e1 hoje?",
	"emoji.subtitle": "Escolha at\u00e9 3",
	"emoji.subtitleFree": "Escolha um",
	"emoji.done": "Pronto",
	// ConnectionCard
	"connection.notOnInko": "Ainda n\u00e3o est\u00e1 no Inko",
	"connection.onVacation": "De f\u00e9rias",
	"connection.removeTitle": "Remover {{name}}?",
	"connection.removeMessage": "A pessoa n\u00e3o ser\u00e1 notificada.",
	"connection.remove": "Remover",
	"connection.block": "Bloquear",
	"connection.blockTitle": "Bloquear {{name}}?",
	"connection.blockMessage":
		"A pessoa n\u00e3o poder\u00e1 adicionar voc\u00ea ao c\u00edrculo dela.",
	"connection.addNickname": "Adicionar apelido",
	"connection.editNickname": "Editar apelido",
	"connection.nicknamePlaceholder": "Digite um apelido",
	"connection.nicknameSave": "Salvar",
	"connection.nicknameTitle": "Apelido para {{name}}",
	"connection.missedDeadline": "Prazo perdido",
	"connection.days": "{{count}} dias",
	// ConnectionsList
	"circle.title": "Seu C\u00edrculo",
	"circle.empty": "Seu c\u00edrculo est\u00e1 vazio",
	"circle.emptyHint":
		"Toque no \u00edcone de pessoas para adicionar algu\u00e9m",
	"circle.emptyAction": "Adicionar pessoas",
	"circle.errorTitle": "N\u00e3o foi poss\u00edvel carregar seu c\u00edrculo",
	"circle.errorRetry": "Tentar novamente",
	"circle.complete": "C\u00edrculo completo!",
	// Settings
	"settings.title": "Configura\u00e7\u00f5es",
	"settings.account": "Conta",
	"settings.username": "Nome de usu\u00e1rio",
	"settings.emailAddress": "E-mail",
	"settings.name": "Nome",
	"settings.timezone": "Fuso hor\u00e1rio",
	"settings.selectTimezone": "Selecionar fuso hor\u00e1rio",
	"settings.searchTimezone": "Pesquisar fusos hor\u00e1rios...",
	"settings.errorTimezone":
		"N\u00e3o foi poss\u00edvel atualizar o fuso hor\u00e1rio",
	"settings.dailyDeadline": "Prazo di\u00e1rio",
	"settings.change": "alterar",
	"settings.reminderHint": "Lembretes em 5h, 1h e 15 min antes.",
	"settings.vacationMode": "Modo f\u00e9rias",
	"settings.vacationHint":
		"Ativo por 1 semana. Pausa lembretes e preserva sequ\u00eancias.",
	"settings.vacationStart": "Iniciar f\u00e9rias de 7 dias?",
	"settings.vacationStartConfirm": "As sequ\u00eancias ser\u00e3o preservadas.",
	"settings.vacationEndEarly": "Encerrar f\u00e9rias mais cedo?",
	"settings.vacationDaysLeft": "{{count}} dias restantes",
	"settings.selectLanguage": "Selecionar idioma",
	"settings.language": "Idioma",
	"settings.signOut": "Sair",
	"settings.deleteAccount": "Excluir conta",
	"settings.version": "inko v{{version}}",
	"settings.signOutTitle": "Sair",
	"settings.signOutConfirm": "Tem certeza?",
	"settings.deleteTitle": "Excluir conta",
	"settings.deleteMessage":
		"Isso excluir\u00e1 permanentemente sua conta e todos os dados. N\u00e3o pode ser desfeito.",
	"settings.delete": "Excluir",
	"settings.updateFailed": "Falha na atualiza\u00e7\u00e3o",
	"settings.errorVacation":
		"N\u00e3o foi poss\u00edvel atualizar o modo f\u00e9rias",
	"settings.errorDeadline": "N\u00e3o foi poss\u00edvel atualizar o prazo",
	"settings.errorLanguage": "N\u00e3o foi poss\u00edvel atualizar o idioma",
	"settings.circleComplete": "Notifica\u00e7\u00e3o de c\u00edrculo completo",
	"settings.circleCompleteHint":
		"Receba uma notifica\u00e7\u00e3o quando todos do seu c\u00edrculo fizerem check-in.",
	"settings.largeText": "Texto grande",
	"settings.largeTextHint":
		"Aumenta o tamanho do texto para facilitar a leitura.",
	"settings.privacyPolicy": "Pol\u00edtica de Privacidade",
	"settings.plan": "Plano",
	"settings.premiumActive": "Premium",
	"settings.upgradeToPremium": "Atualizar para Premium",
	// TimePickerModal
	"timePicker.title": "Definir prazo di\u00e1rio",
	// Add Person
	"addPerson.title": "Adicionar pessoa",
	"addPerson.fromContacts": "Dos contatos",
	"addPerson.usernameLabel": "Nome de usu\u00e1rio",
	"addPerson.usernamePlaceholder": "ex. eriksson42",
	"addPerson.add": "Adicionar",
	"addPerson.errorUsername": "Digite um nome de usu\u00e1rio",
	"addPerson.errorNotFound": "Nenhum usu\u00e1rio encontrado com esse nome",
	"addPerson.errorAdd": "N\u00e3o foi poss\u00edvel adicionar a pessoa",
	"addPerson.errorGeneric": "Algo deu errado",
	// Contacts
	"contacts.title": "Adicionar pessoas",
	"contacts.search": "Buscar contatos...",
	"contacts.onInko": "NO INKO ({{count}})",
	"contacts.invite": "CONVIDAR ({{count}})",
	"contacts.onInkoBadge": "no inko",
	"contacts.addToCircle": "Adicionar {{count}} ao c\u00edrculo",
	"contacts.inviteFriends": "Convidar amigos",
	"contacts.inviteButton": "Convidar",
	"contacts.permissionTitle": "Acesso aos contatos necess\u00e1rio",
	"contacts.permissionMessage":
		"Permita que o Inko acesse seus contatos para encontrar pessoas que voc\u00ea conhece.",
	"contacts.openSettings": "Abrir Configura\u00e7\u00f5es",
	"contacts.noContacts": "Nenhum contato encontrado",
	"contacts.manualEntry": "Adicionar por nome de usu\u00e1rio",
	"contacts.noContactsMessage":
		"Nenhum contato com n\u00famero de telefone v\u00e1lido foi encontrado no seu dispositivo.",
	// Date/time
	"time.justNow": "agora mesmo",
	"time.minutesAgo": "{{count}}min atr\u00e1s",
	"time.hoursAgo": "{{count}}h atr\u00e1s",
	// Share invite
	"invite.message":
		"Oi! Eu uso o Inko para fazer check-in com meu c\u00edrculo todo dia. Vem comigo!\n\nMeu usuário: {{username}}\n\nAndroid: https://play.google.com/store/apps/details?id=com.inko.app\niOS: https://apps.apple.com/app/id6759858427",
	// Notification action buttons
	"notification.action.inkoNow": "Inka agora",
	"notification.action.reachOut": "Entrar em contato",
	// Notifications
	"notifications.requiredTitle": "Notifica\u00e7\u00f5es necess\u00e1rias",
	"notifications.requiredMessage":
		"O Inko precisa de notifica\u00e7\u00f5es para lembrar voc\u00ea de inkar e avisar quando seu c\u00edrculo estiver completo.",
	"notifications.openSettings": "Abrir Configurações",
	"notifications.statusEnabled": "Ativadas",
	"notifications.statusDisabled": "Desativadas — toque para corrigir",
	"notifications.pushNotifications": "Notificações push",
	// Spotlight
	"spotlight.step1Title": "Bem-vindo ao Inko",
	"spotlight.step1Subtitle":
		"Um check-in di\u00e1rio com sua galera.\nUm emoji por dia. S\u00f3 isso.",
	"spotlight.step2Title": "Toque. Sinta. Compartilhe.",
	"spotlight.step2Subtitle":
		"Toque no cora\u00e7\u00e3o e escolha at\u00e9 3 emojis\nque representem seu dia.",
	"spotlight.step3Title": "Seu C\u00edrculo",
	"spotlight.step3Subtitle":
		"Adicione as pessoas que importam.\nVeja quando elas fazem check-in.",
	"spotlight.step4Title": "Fique no ritmo",
	"spotlight.step4Subtitle":
		"Receba lembretes antes do seu prazo.\n\u00c0 meia-noite, tudo recome\u00e7a. Precisa de uma pausa?\nAtive o Modo F\u00e9rias nas configura\u00e7\u00f5es.",
	"spotlight.next": "Pr\u00f3ximo",
	"spotlight.letsGo": "Vamos l\u00e1",
	// Streak
	"streak.own": "Sequ\u00eancia de {{count}} dias",
	// Premium
	"premium.title": "Desbloquear Premium",
	"premium.subtitle": "Tenha a experi\u00eancia completa do Inko.",
	"premium.featureEmojis": "50 emojis para escolher",
	"premium.featureMultiEmoji": "Escolha at\u00e9 3 emojis por check-in",
	"premium.unlock": "Desbloquear por {{price}}",
	"premium.unlockWeb": "Desbloquear Premium",
	"premium.restore": "Restaurar compra",
	"premium.restoring": "Restaurando...",
	// Common
	"common.cancel": "Cancelar",
	"common.close": "Fechar",
	// Language names
	"language.en": "English",
	"language.sv": "Svenska",
	"language.es": "Espa\u00f1ol",
	"language.pt": "Portugu\u00eas",
};
export const emojis = [
	// Core (same as free)
	"😊",
	"😎",
	"😴",
	"😤",
	"😢",
	"🤒",
	"🥳",
	"💪",
	"☕",
	"❤️",
	"🙏",
	"☀️",
	"🌧️",
	"😐",
	"🤔",
	"😅",
	"🫶",
	"🏠",
	// Premium extras
	"🛌",
	"👋",
	"🥱",
	"🏃",
	"📚",
	"💻",
	"🎉",
	"🍕",
	"🎵",
	"✈️",
	"🧘",
	"🍷",
	"🔥",
	"🌈",
	"🎯",
	"🧠",
	"💤",
	"🤩",
	"😇",
	"🥰",
	"🤗",
	"😭",
	"🫠",
	"🤯",
	"🥶",
	"🤝",
	"👏",
	"🎶",
	"🌸",
	"⭐",
	"🍀",
	"🐶",
];
export const translations = { en, sv, es, pt };
